### ISSUE TITLE
Remove: doocs-fred-eqfct 

### ISSUE THREAD

**Issue by vargheseg** [ChimeraTK/DebianBuildVersions#2]
`doocs-fred-eqfct`   was previously needed by the doocs-fred-server. This is not true anymore, plus the project probably will not be maintained.

**Comment by mhier** [comment]
Along with it, the following projects can also be removed (pay attention, similarly-named projects must be kept!):
- doocs-llrfctrlcmtbsincav-server
- doocs-llrfctrlhzdr-server
- opcua-llrfctrlhzdr-server
- mtca4u-deviceaccess

**Comment by mhier** [comment]
Do we keep some kind of archive for old projects?

**Comment by vargheseg** [comment]
30ff8f5cd83684db237966c8cf78dfb791930930 closes this ticket
